version: "3.8"

services:
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true